version: "2"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.1
    container_name: userline-kibana
    restart: always
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - xpack.security.enable=false
      - xpack.monitoring.enable=false
      - xpack.ml.enable=false
      - xpack.graph.enable=false
      - xpack.watcher.enable=false
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    container_name: userline-elasticsearch
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - cluster.name=userline
      - xpack.security.enable=false
      - xpack.monitoring.enable=false
      - xpack.ml.enable=false
      - xpack.graph.enable=false
      - xpack.watcher.enable=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  neo4j:
    image: neo4j:3.2
    container_name: userline-neo4j
    restart: always
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neodata:/data

volumes:
  neodata:
  esdata:
